# Generated by Django 2.0.9 on 2019-01-14 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('exam_type', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(blank=True, max_length=64)),
                ('available_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
