# Generated by Django 2.0.9 on 2019-01-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='available_time',
        ),
        migrations.AddField(
            model_name='exam',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='taken_people',
            field=models.IntegerField(default=0),
        ),
    ]
