# Generated by Django 2.0.9 on 2019-01-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='phrase',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='relate',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.Phrase'),
        ),
        migrations.AddField(
            model_name='relate',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.Word'),
        ),
    ]
